package miniapp

// provincialData 国内省级/城市数据
var provincialData = []ProvinceCity{
	{
		Province: "北京",
		Cities:   []string{"东城区", "西城区", "朝阳区", "海淀区", "丰台区", "石景山区", "通州区", "大兴区", "顺义区", "房山区", "昌平区", "密云区", "怀柔区", "延庆区", "平谷区", "门头沟区"},
	},
	{
		Province: "上海",
		Cities:   []string{"黄浦区", "徐汇区", "长宁区", "静安区", "普陀区", "虹口区", "杨浦区", "浦东新区", "闵行区", "宝山区", "嘉定区", "金山区", "松江区", "青浦区", "奉贤区", "崇明区"},
	},
	{
		Province: "天津",
		Cities:   []string{"和平区", "河东区", "河西区", "南开区", "河北区", "红桥区", "滨海新区", "东丽区", "西青区", "津南区", "北辰区", "武清区", "宝坻区", "宁河区", "静海区", "蓟州区"},
	},
	{
		Province: "重庆",
		Cities:   []string{"渝中区", "江北区", "南岸区", "沙坪坝区", "九龙坡区", "大渡口区", "北碚区", "渝北区", "巴南区", "万州区", "涪陵区", "黔江区", "永川区", "合川区", "江津区", "长寿区", "綦江区", "大足区", "铜梁区", "璧山区", "荣昌区", "开州区", "梁平区", "武隆区", "潼南区", "丰都县", "垫江县", "忠县", "云阳县", "奉节县", "巫山县", "巫溪县", "石柱土家族自治县", "秀山土家族苗族自治县", "酉阳土家族苗族自治县", "彭水苗族土家族自治县"},
	},
	{
		Province: "河北",
		Cities:   []string{"石家庄", "唐山", "秦皇岛", "邯郸", "邢台", "保定", "张家口", "承德", "沧州", "廊坊", "衡水"},
	},
	{
		Province: "山西",
		Cities:   []string{"太原", "大同", "阳泉", "长治", "晋城", "朔州", "晋中", "运城", "忻州", "临汾", "吕梁"},
	},
	{
		Province: "内蒙古",
		Cities:   []string{"呼和浩特", "包头", "乌海", "赤峰", "通辽", "鄂尔多斯", "呼伦贝尔", "巴彦淖尔", "乌兰察布", "兴安盟", "锡林郭勒盟", "阿拉善盟"},
	},
	{
		Province: "辽宁",
		Cities:   []string{"沈阳", "大连", "鞍山", "抚顺", "本溪", "丹东", "锦州", "营口", "阜新", "辽阳", "盘锦", "铁岭", "朝阳", "葫芦岛"},
	},
	{
		Province: "吉林",
		Cities:   []string{"长春", "吉林", "四平", "辽源", "通化", "白山", "松原", "白城", "延边"},
	},
	{
		Province: "黑龙江",
		Cities:   []string{"哈尔滨", "齐齐哈尔", "鸡西", "鹤岗", "双鸭山", "大庆", "伊春", "佳木斯", "七台河", "牡丹江", "黑河", "绥化", "大兴安岭"},
	},
	{
		Province: "江苏",
		Cities:   []string{"南京", "无锡", "徐州", "常州", "苏州", "南通", "连云港", "淮安", "盐城", "扬州", "镇江", "泰州", "宿迁"},
	},
	{
		Province: "浙江",
		Cities:   []string{"杭州", "宁波", "温州", "嘉兴", "湖州", "绍兴", "金华", "衢州", "舟山", "台州", "丽水"},
	},
	{
		Province: "安徽",
		Cities:   []string{"合肥", "芜湖", "蚌埠", "淮南", "马鞍山", "淮北", "铜陵", "安庆", "黄山", "滁州", "阜阳", "宿州", "六安", "亳州", "池州", "宣城"},
	},
	{
		Province: "福建",
		Cities:   []string{"福州", "厦门", "莆田", "三明", "泉州", "漳州", "南平", "龙岩", "宁德"},
	},
	{
		Province: "江西",
		Cities:   []string{"南昌", "景德镇", "萍乡", "九江", "新余", "鹰潭", "赣州", "吉安", "宜春", "抚州", "上饶"},
	},
	{
		Province: "山东",
		Cities:   []string{"济南", "青岛", "淄博", "枣庄", "东营", "烟台", "潍坊", "济宁", "泰安", "威海", "日照", "临沂", "德州", "聊城", "滨州", "菏泽"},
	},
	{
		Province: "河南",
		Cities:   []string{"郑州", "开封", "洛阳", "平顶山", "安阳", "鹤壁", "新乡", "焦作", "濮阳", "许昌", "漯河", "三门峡", "南阳", "商丘", "信阳", "周口", "驻马店", "济源"},
	},
	{
		Province: "湖北",
		Cities:   []string{"武汉", "黄石", "十堰", "宜昌", "襄阳", "鄂州", "荆门", "孝感", "荆州", "黄冈", "咸宁", "随州", "恩施", "仙桃", "潜江", "天门", "神农架"},
	},
	{
		Province: "湖南",
		Cities:   []string{"长沙", "株洲", "湘潭", "衡阳", "邵阳", "岳阳", "常德", "张家界", "益阳", "郴州", "永州", "怀化", "娄底", "湘西"},
	},
	{
		Province: "广东",
		Cities:   []string{"广州", "深圳", "珠海", "汕头", "佛山", "韶关", "湛江", "肇庆", "江门", "茂名", "惠州", "梅州", "汕尾", "河源", "阳江", "清远", "东莞", "中山", "潮州", "揭阳", "云浮"},
	},
	{
		Province: "广西",
		Cities:   []string{"南宁", "柳州", "桂林", "梧州", "北海", "防城港", "钦州", "贵港", "玉林", "百色", "贺州", "河池", "来宾", "崇左"},
	},
	{
		Province: "海南",
		Cities:   []string{"海口", "三亚", "三沙", "儋州", "五指山", "琼海", "文昌", "万宁", "东方", "定安", "屯昌", "澄迈", "临高", "白沙", "昌江", "乐东", "陵水", "保亭", "琼中"},
	},
	{
		Province: "四川",
		Cities:   []string{"成都", "自贡", "攀枝花", "泸州", "德阳", "绵阳", "广元", "遂宁", "内江", "乐山", "南充", "眉山", "宜宾", "广安", "达州", "雅安", "巴中", "资阳", "阿坝", "甘孜", "凉山"},
	},
	{
		Province: "贵州",
		Cities:   []string{"贵阳", "六盘水", "遵义", "安顺", "毕节", "铜仁", "黔西南", "黔东南", "黔南"},
	},
	{
		Province: "云南",
		Cities:   []string{"昆明", "曲靖", "玉溪", "保山", "昭通", "丽江", "普洱", "临沧", "楚雄", "红河", "文山", "西双版纳", "大理", "德宏", "怒江", "迪庆"},
	},
	{
		Province: "西藏",
		Cities:   []string{"拉萨", "日喀则", "昌都", "林芝", "山南", "那曲", "阿里"},
	},
	{
		Province: "陕西",
		Cities:   []string{"西安", "铜川", "宝鸡", "咸阳", "渭南", "延安", "汉中", "榆林", "安康", "商洛"},
	},
	{
		Province: "甘肃",
		Cities:   []string{"兰州", "嘉峪关", "金昌", "白银", "天水", "武威", "张掖", "平凉", "酒泉", "庆阳", "定西", "陇南", "临夏", "甘南"},
	},
	{
		Province: "青海",
		Cities:   []string{"西宁", "海东", "海北", "黄南", "海南", "果洛", "玉树", "海西"},
	},
	{
		Province: "宁夏",
		Cities:   []string{"银川", "石嘴山", "吴忠", "固原", "中卫"},
	},
	{
		Province: "新疆",
		Cities:   []string{"乌鲁木齐", "克拉玛依", "吐鲁番", "哈密", "昌吉", "博尔塔拉", "巴音郭楞", "阿克苏", "克孜勒苏", "喀什", "和田", "伊犁", "塔城", "阿勒泰"},
	},
	{
		Province: "香港",
		Cities:   []string{"中西区", "湾仔区", "东区", "南区", "油尖旺区", "深水埗区", "九龙城区", "黄大仙区", "观塘区", "荃湾区", "屯门区", "元朗区", "北区", "大埔区", "西贡区", "沙田区", "葵青区", "离岛区"},
	},
	{
		Province: "澳门",
		Cities:   []string{"花地玛堂区", "圣安多尼堂区", "大堂区", "望德堂区", "风顺堂区", "嘉模堂区", "路氹城", "圣方济各堂区"},
	},
	{
		Province: "台湾",
		Cities:   []string{"台北", "高雄", "基隆", "台中", "台南", "新竹", "嘉义", "新北", "桃园", "新竹市", "苗栗", "彰化", "南投", "云林", "嘉义市", "屏东", "宜兰", "花莲", "台东", "澎湖", "金门", "连江"},
	},
}

// countryData 境外国家/地区列表
var countryData = []CountryItem{
	{Code: "JP", Name: "日本", NameEn: "Japan", Emoji: "🇯🇵", Phone: "+81"},
	{Code: "KR", Name: "韩国", NameEn: "South Korea", Emoji: "🇰🇷", Phone: "+82"},
	{Code: "TH", Name: "泰国", NameEn: "Thailand", Emoji: "🇹🇭", Phone: "+66"},
	{Code: "SG", Name: "新加坡", NameEn: "Singapore", Emoji: "🇸🇬", Phone: "+65"},
	{Code: "MY", Name: "马来西亚", NameEn: "Malaysia", Emoji: "🇲🇾", Phone: "+60"},
	{Code: "VN", Name: "越南", NameEn: "Vietnam", Emoji: "🇻🇳", Phone: "+84"},
	{Code: "PH", Name: "菲律宾", NameEn: "Philippines", Emoji: "🇵🇭", Phone: "+63"},
	{Code: "ID", Name: "印度尼西亚", NameEn: "Indonesia", Emoji: "🇮🇩", Phone: "+62"},
	{Code: "KH", Name: "柬埔寨", NameEn: "Cambodia", Emoji: "🇰🇭", Phone: "+855"},
	{Code: "LA", Name: "老挝", NameEn: "Laos", Emoji: "🇱🇦", Phone: "+856"},
	{Code: "MM", Name: "缅甸", NameEn: "Myanmar", Emoji: "🇲🇲", Phone: "+95"},
	{Code: "BN", Name: "文莱", NameEn: "Brunei", Emoji: "🇧🇳", Phone: "+673"},
	{Code: "TL", Name: "东帝汶", NameEn: "Timor-Leste", Emoji: "🇹🇱", Phone: "+670"},
	{Code: "NP", Name: "尼泊尔", NameEn: "Nepal", Emoji: "🇳🇵", Phone: "+977"},
	{Code: "BT", Name: "不丹", NameEn: "Bhutan", Emoji: "🇧🇹", Phone: "+975"},
	{Code: "BD", Name: "孟加拉国", NameEn: "Bangladesh", Emoji: "🇧🇩", Phone: "+880"},
	{Code: "LK", Name: "斯里兰卡", NameEn: "Sri Lanka", Emoji: "🇱🇰", Phone: "+94"},
	{Code: "MV", Name: "马尔代夫", NameEn: "Maldives", Emoji: "🇲🇻", Phone: "+960"},
	{Code: "IN", Name: "印度", NameEn: "India", Emoji: "🇮🇳", Phone: "+91"},
	{Code: "PK", Name: "巴基斯坦", NameEn: "Pakistan", Emoji: "🇵🇰", Phone: "+92"},
	{Code: "KZ", Name: "哈萨克斯坦", NameEn: "Kazakhstan", Emoji: "🇰🇿", Phone: "+7"},
	{Code: "UZ", Name: "乌兹别克斯坦", NameEn: "Uzbekistan", Emoji: "🇺🇿", Phone: "+998"},
	{Code: "KG", Name: "吉尔吉斯斯坦", NameEn: "Kyrgyzstan", Emoji: "🇰🇬", Phone: "+996"},
	{Code: "TJ", Name: "塔吉克斯坦", NameEn: "Tajikistan", Emoji: "🇹🇯", Phone: "+992"},
	{Code: "TM", Name: "土库曼斯坦", NameEn: "Turkmenistan", Emoji: "🇹🇲", Phone: "+993"},
	{Code: "MN", Name: "蒙古", NameEn: "Mongolia", Emoji: "🇲🇳", Phone: "+976"},
	{Code: "AE", Name: "阿联酋", NameEn: "United Arab Emirates", Emoji: "🇦🇪", Phone: "+971"},
	{Code: "SA", Name: "沙特阿拉伯", NameEn: "Saudi Arabia", Emoji: "🇸🇦", Phone: "+966"},
	{Code: "QA", Name: "卡塔尔", NameEn: "Qatar", Emoji: "🇶🇦", Phone: "+974"},
	{Code: "KW", Name: "科威特", NameEn: "Kuwait", Emoji: "🇰🇼", Phone: "+965"},
	{Code: "OM", Name: "阿曼", NameEn: "Oman", Emoji: "🇴🇲", Phone: "+968"},
	{Code: "BH", Name: "巴林", NameEn: "Bahrain", Emoji: "🇧🇭", Phone: "+973"},
	{Code: "TR", Name: "土耳其", NameEn: "Turkey", Emoji: "🇹🇷", Phone: "+90"},
	{Code: "IL", Name: "以色列", NameEn: "Israel", Emoji: "🇮🇱", Phone: "+972"},
	{Code: "JO", Name: "约旦", NameEn: "Jordan", Emoji: "🇯🇴", Phone: "+962"},
	{Code: "IR", Name: "伊朗", NameEn: "Iran", Emoji: "🇮🇷", Phone: "+98"},
	{Code: "GB", Name: "英国", NameEn: "United Kingdom", Emoji: "🇬🇧", Phone: "+44"},
	{Code: "FR", Name: "法国", NameEn: "France", Emoji: "🇫🇷", Phone: "+33"},
	{Code: "DE", Name: "德国", NameEn: "Germany", Emoji: "🇩🇪", Phone: "+49"},
	{Code: "IT", Name: "意大利", NameEn: "Italy", Emoji: "🇮🇹", Phone: "+39"},
	{Code: "ES", Name: "西班牙", NameEn: "Spain", Emoji: "🇪🇸", Phone: "+34"},
	{Code: "PT", Name: "葡萄牙", NameEn: "Portugal", Emoji: "🇵🇹", Phone: "+351"},
	{Code: "NL", Name: "荷兰", NameEn: "Netherlands", Emoji: "🇳🇱", Phone: "+31"},
	{Code: "BE", Name: "比利时", NameEn: "Belgium", Emoji: "🇧🇪", Phone: "+32"},
	{Code: "CH", Name: "瑞士", NameEn: "Switzerland", Emoji: "🇨🇭", Phone: "+41"},
	{Code: "AT", Name: "奥地利", NameEn: "Austria", Emoji: "🇦🇹", Phone: "+43"},
	{Code: "SE", Name: "瑞典", NameEn: "Sweden", Emoji: "🇸🇪", Phone: "+46"},
	{Code: "NO", Name: "挪威", NameEn: "Norway", Emoji: "🇳🇴", Phone: "+47"},
	{Code: "DK", Name: "丹麦", NameEn: "Denmark", Emoji: "🇩🇰", Phone: "+45"},
	{Code: "FI", Name: "芬兰", NameEn: "Finland", Emoji: "🇫🇮", Phone: "+358"},
	{Code: "IS", Name: "冰岛", NameEn: "Iceland", Emoji: "🇮🇸", Phone: "+354"},
	{Code: "IE", Name: "爱尔兰", NameEn: "Ireland", Emoji: "🇮🇪", Phone: "+353"},
	{Code: "GR", Name: "希腊", NameEn: "Greece", Emoji: "🇬🇷", Phone: "+30"},
	{Code: "PL", Name: "波兰", NameEn: "Poland", Emoji: "🇵🇱", Phone: "+48"},
	{Code: "CZ", Name: "捷克", NameEn: "Czech Republic", Emoji: "🇨🇿", Phone: "+420"},
	{Code: "HU", Name: "匈牙利", NameEn: "Hungary", Emoji: "🇭🇺", Phone: "+36"},
	{Code: "RO", Name: "罗马尼亚", NameEn: "Romania", Emoji: "🇷🇴", Phone: "+40"},
	{Code: "BG", Name: "保加利亚", NameEn: "Bulgaria", Emoji: "🇧🇬", Phone: "+359"},
	{Code: "RS", Name: "塞尔维亚", NameEn: "Serbia", Emoji: "🇷🇸", Phone: "+381"},
	{Code: "HR", Name: "克罗地亚", NameEn: "Croatia", Emoji: "🇭🇷", Phone: "+385"},
	{Code: "RU", Name: "俄罗斯", NameEn: "Russia", Emoji: "🇷🇺", Phone: "+7"},
	{Code: "UA", Name: "乌克兰", NameEn: "Ukraine", Emoji: "🇺🇦", Phone: "+380"},
	{Code: "US", Name: "美国", NameEn: "United States", Emoji: "🇺🇸", Phone: "+1"},
	{Code: "CA", Name: "加拿大", NameEn: "Canada", Emoji: "🇨🇦", Phone: "+1"},
	{Code: "MX", Name: "墨西哥", NameEn: "Mexico", Emoji: "🇲🇽", Phone: "+52"},
	{Code: "AU", Name: "澳大利亚", NameEn: "Australia", Emoji: "🇦🇺", Phone: "+61"},
	{Code: "NZ", Name: "新西兰", NameEn: "New Zealand", Emoji: "🇳🇿", Phone: "+64"},
	{Code: "FJ", Name: "斐济", NameEn: "Fiji", Emoji: "🇫🇯", Phone: "+679"},
	{Code: "PG", Name: "巴布亚新几内亚", NameEn: "Papua New Guinea", Emoji: "🇵🇬", Phone: "+675"},
	{Code: "EG", Name: "埃及", NameEn: "Egypt", Emoji: "🇪🇬", Phone: "+20"},
	{Code: "ZA", Name: "南非", NameEn: "South Africa", Emoji: "🇿🇦", Phone: "+27"},
	{Code: "KE", Name: "肯尼亚", NameEn: "Kenya", Emoji: "🇰🇪", Phone: "+254"},
	{Code: "MA", Name: "摩洛哥", NameEn: "Morocco", Emoji: "🇲🇦", Phone: "+212"},
	{Code: "MU", Name: "毛里求斯", NameEn: "Mauritius", Emoji: "🇲🇺", Phone: "+230"},
	{Code: "SC", Name: "塞舌尔", NameEn: "Seychelles", Emoji: "🇸🇨", Phone: "+248"},
	{Code: "AR", Name: "阿根廷", NameEn: "Argentina", Emoji: "🇦🇷", Phone: "+54"},
	{Code: "BR", Name: "巴西", NameEn: "Brazil", Emoji: "🇧🇷", Phone: "+55"},
	{Code: "CL", Name: "智利", NameEn: "Chile", Emoji: "🇨🇱", Phone: "+56"},
	{Code: "PE", Name: "秘鲁", NameEn: "Peru", Emoji: "🇵🇪", Phone: "+51"},
	{Code: "CO", Name: "哥伦比亚", NameEn: "Colombia", Emoji: "🇨🇴", Phone: "+57"},
	{Code: "CU", Name: "古巴", NameEn: "Cuba", Emoji: "🇨🇺", Phone: "+53"},
	{Code: "CR", Name: "哥斯达黎加", NameEn: "Costa Rica", Emoji: "🇨🇷", Phone: "+506"},
}
